# Generated by Django 5.2.8 on 2025-11-26 20:21

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('limite_crediario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('saldo_devedor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clientes',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['telefone'], name='idx_clientes_telefone'), models.Index(fields=['saldo_devedor'], name='idx_clientes_saldo')],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.CharField(blank=True, max_length=50, null=True)),
                ('data_nota', models.DateField(default=django.utils.timezone.localdate)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('parcial', 'Parcial'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='crediario.cliente')),
            ],
            options={
                'db_table': 'notas',
                'ordering': ['-data_nota'],
            },
        ),
        migrations.CreateModel(
            name='ItemNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('quantidade', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=18)),
                ('preco_unitario', models.DecimalField(decimal_places=4, max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='crediario.nota')),
            ],
            options={
                'db_table': 'itens_nota',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='notas/')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('tamanho_bytes', models.BigIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='crediario.nota')),
            ],
            options={
                'db_table': 'anexos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('canal', models.CharField(default='log', max_length=20)),
                ('destinatario', models.CharField(blank=True, max_length=200, null=True)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pendente', max_length=20)),
                ('tentativa', models.IntegerField(default=0)),
                ('data_agendada', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes', to='crediario.cliente')),
                ('nota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes', to='crediario.nota')),
            ],
            options={
                'db_table': 'notificacoes',
                'ordering': ['-data_agendada', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_pagamento', models.DateField(default=django.utils.timezone.localdate)),
                ('metodo', models.CharField(blank=True, max_length=50, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='crediario.cliente')),
                ('nota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to='crediario.nota')),
            ],
            options={
                'db_table': 'pagamentos',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['vencimento'], name='idx_notas_vencimento'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['status', 'data_nota'], name='idx_notas_status_data'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['nota', 'tipo', 'data_agendada'], name='idx_notif_nota_tipo_data'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['nota'], name='idx_pagamentos_nota'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['cliente'], name='idx_pagamentos_cliente'),
        ),
    ]
